name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build images
        run: docker compose build

      - name: Start stack
        run: docker compose up -d
